nelmio_api_doc:
    documentation:
        info:
            title: Symfony JWT App
            version: 0.0.1
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Authorization: Bearer {jwt}'
                name: Authorization
                in: header
                scheme: Bearer
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/api(?!/doc$)